LOG_FOLDER = "logs"
UPLOAD_FOLDER = "uploads"
ROWS_PER_PAGE = 20
DRIVE_FOLDER_ID = "YOUR-DRIVE-FOLDER-ID"
SPREADSHEET_ID = "YOUR-SPREADHSEET-ID"
ALLOWED_EXTENSIONS = {".pdf", ".jpg", ".jpeg", ".png"}
SECRET_KEY = "YOUR-FLASK-SECRET"
